# ===================== 시스템 기본 =====================
- ros_topic_name: /clock
  gz_topic_name: /clock
  ros_type_name: rosgraph_msgs/msg/Clock
  gz_type_name: gz.msgs.Clock
  direction: GZ_TO_ROS

# ===================== Jetank 카메라 =====================
# camera image
- ros_topic_name: "/jetank1/camera/image_raw"
  gz_topic_name: "camera/image_raw"
  ros_type_name: "sensor_msgs/msg/Image"
  gz_type_name: "gz.msgs.Image"
  direction: GZ_TO_ROS

# camera info
- ros_topic_name: "/jetank1/camera/camera_info"
  gz_topic_name: "camera/camera_info"
  ros_type_name: "sensor_msgs/msg/CameraInfo"
  gz_type_name: "gz.msgs.CameraInfo"
  direction: GZ_TO_ROS

# ===================== Jetank 관절 상태 =====================
- ros_topic_name: /jetank1/joint_states
  gz_topic_name: /world/default/model/jetank1/joint_state
  ros_type_name: sensor_msgs/msg/JointState
  gz_type_name: gz.msgs.Model
  direction: GZ_TO_ROS
# ===================== Jetank 카메라 =====================
# camera image
- ros_topic_name: "/jetank2/camera/image_raw"
  gz_topic_name: "camera/image_raw"
  ros_type_name: "sensor_msgs/msg/Image"
  gz_type_name: "gz.msgs.Image"
  direction: GZ_TO_ROS

# camera info
- ros_topic_name: "/jetank2/camera/camera_info"
  gz_topic_name: "camera/camera_info"
  ros_type_name: "sensor_msgs/msg/CameraInfo"
  gz_type_name: "gz.msgs.CameraInfo"
  direction: GZ_TO_ROS

# ===================== Jetank 관절 상태 =====================
- ros_topic_name: /jetank2/joint_states
  gz_topic_name: /world/default/model/jetank2/joint_state
  ros_type_name: sensor_msgs/msg/JointState
  gz_type_name: gz.msgs.Model
  direction: GZ_TO_ROS
#================= 컨베이어 벨트 조정 =========================

- ros_topic_name: "/jetank/conveyor_belt/tf"
  gz_topic_name: "/model/conveyor_belt/pose"
  ros_type_name: "tf2_msgs/msg/TFMessage"
  gz_type_name: "gz.msgs.Pose_V"
  direction: GZ_TO_ROS
  
- ros_topic_name: "/jetank/conveyor/power"
  gz_topic_name: "/conveyor/power"
  ros_type_name: "std_srvs/srv/SetBool"
  gz_type_name: "gz.msgs.Boolean"

# ================= 젠가 부착/해제 명령 (1~10) =================
# ROS (std_msgs/Empty) -> Gazebo (ignition.msgs.Empty)

# Jenga 1
- ros_topic_name: "/jetank1/jenga1/attach"
  gz_topic_name: "/jetank1/jenga1/attach"
  ros_type_name: "std_msgs/msg/Empty"
  gz_type_name: "ignition.msgs.Empty"
  direction: "ROS_TO_GZ"
- ros_topic_name: "/jetank1/jenga1/detach"
  gz_topic_name: "/jetank1/jenga1/detach"
  ros_type_name: "std_msgs/msg/Empty"
  gz_type_name: "ignition.msgs.Empty"
  direction: "ROS_TO_GZ"
# Jenga 2
- ros_topic_name: "/jetank1/jenga2/attach"
  gz_topic_name: "/jetank1/jenga2/attach"
  ros_type_name: "std_msgs/msg/Empty"
  gz_type_name: "ignition.msgs.Empty"
  direction: "ROS_TO_GZ"
- ros_topic_name: "/jetank1/jenga2/detach"
  gz_topic_name: "/jetank1/jenga2/detach"
  ros_type_name: "std_msgs/msg/Empty"
  gz_type_name: "ignition.msgs.Empty"
  direction: "ROS_TO_GZ"
# Jenga 3
- ros_topic_name: "/jetank1/jenga3/attach"
  gz_topic_name: "/jetank1/jenga3/attach"
  ros_type_name: "std_msgs/msg/Empty"
  gz_type_name: "ignition.msgs.Empty"
  direction: "ROS_TO_GZ"
- ros_topic_name: "/jetank1/jenga3/detach"
  gz_topic_name: "/jetank1/jenga3/detach"
  ros_type_name: "std_msgs/msg/Empty"
  gz_type_name: "ignition.msgs.Empty"
  direction: "ROS_TO_GZ"
# Jenga 4
- ros_topic_name: "/jetank1/jenga4/attach"
  gz_topic_name: "/jetank1/jenga4/attach"
  ros_type_name: "std_msgs/msg/Empty"
  gz_type_name: "ignition.msgs.Empty"
  direction: "ROS_TO_GZ"
- ros_topic_name: "/jetank1/jenga4/detach"
  gz_topic_name: "/jetank1/jenga4/detach"
  ros_type_name: "std_msgs/msg/Empty"
  gz_type_name: "ignition.msgs.Empty"
  direction: "ROS_TO_GZ"
# Jenga 5
- ros_topic_name: "/jetank1/jenga5/attach"
  gz_topic_name: "/jetank1/jenga5/attach"
  ros_type_name: "std_msgs/msg/Empty"
  gz_type_name: "ignition.msgs.Empty"
  direction: "ROS_TO_GZ"
- ros_topic_name: "/jetank1/jenga5/detach"
  gz_topic_name: "/jetank1/jenga5/detach"
  ros_type_name: "std_msgs/msg/Empty"
  gz_type_name: "ignition.msgs.Empty"
  direction: "ROS_TO_GZ"
# Jenga 6
- ros_topic_name: "/jetank1/jenga6/attach"
  gz_topic_name: "/jetank1/jenga6/attach"
  ros_type_name: "std_msgs/msg/Empty"
  gz_type_name: "ignition.msgs.Empty"
  direction: "ROS_TO_GZ"
- ros_topic_name: "/jetank1/jenga6/detach"
  gz_topic_name: "/jetank1/jenga6/detach"
  ros_type_name: "std_msgs/msg/Empty"
  gz_type_name: "ignition.msgs.Empty"
  direction: "ROS_TO_GZ"
# Jenga 7
- ros_topic_name: "/jetank1/jenga7/attach"
  gz_topic_name: "/jetank1/jenga7/attach"
  ros_type_name: "std_msgs/msg/Empty"
  gz_type_name: "ignition.msgs.Empty"
  direction: "ROS_TO_GZ"
- ros_topic_name: "/jetank1/jenga7/detach"
  gz_topic_name: "/jetank1/jenga7/detach"
  ros_type_name: "std_msgs/msg/Empty"
  gz_type_name: "ignition.msgs.Empty"
  direction: "ROS_TO_GZ"
# Jenga 8
- ros_topic_name: "/jetank1/jenga8/attach"
  gz_topic_name: "/jetank1/jenga8/attach"
  ros_type_name: "std_msgs/msg/Empty"
  gz_type_name: "ignition.msgs.Empty"
  direction: "ROS_TO_GZ"
- ros_topic_name: "/jetank1/jenga8/detach"
  gz_topic_name: "/jetank1/jenga8/detach"
  ros_type_name: "std_msgs/msg/Empty"
  gz_type_name: "ignition.msgs.Empty"
  direction: "ROS_TO_GZ"
# Jenga 9
- ros_topic_name: "/jetank1/jenga9/attach"
  gz_topic_name: "/jetank1/jenga9/attach"
  ros_type_name: "std_msgs/msg/Empty"
  gz_type_name: "ignition.msgs.Empty"
  direction: "ROS_TO_GZ"
- ros_topic_name: "/jetank1/jenga9/detach"
  gz_topic_name: "/jetank1/jenga9/detach"
  ros_type_name: "std_msgs/msg/Empty"
  gz_type_name: "ignition.msgs.Empty"
  direction: "ROS_TO_GZ"
# Jenga 10
- ros_topic_name: "/jetank1/jenga10/attach"
  gz_topic_name: "/jetank1/jenga10/attach"
  ros_type_name: "std_msgs/msg/Empty"
  gz_type_name: "ignition.msgs.Empty"
  direction: "ROS_TO_GZ"
- ros_topic_name: "/jetank1/jenga10/detach"
  gz_topic_name: "/jetank1/jenga10/detach"
  ros_type_name: "std_msgs/msg/Empty"
  gz_type_name: "ignition.msgs.Empty"
  direction: "ROS_TO_GZ"
  
#==============jetank2와 jenga연결

# Jenga 1
- ros_topic_name: "/jetank2/jenga1/attach"
  gz_topic_name: "/jetank2/jenga1/attach"
  ros_type_name: "std_msgs/msg/Empty"
  gz_type_name: "ignition.msgs.Empty"
  direction: "ROS_TO_GZ"
- ros_topic_name: "/jetank2/jenga1/detach"
  gz_topic_name: "/jetank2/jenga1/detach"
  ros_type_name: "std_msgs/msg/Empty"
  gz_type_name: "ignition.msgs.Empty"
  direction: "ROS_TO_GZ"
# Jenga 2
- ros_topic_name: "/jetank2/jenga2/attach"
  gz_topic_name: "/jetank2/jenga2/attach"
  ros_type_name: "std_msgs/msg/Empty"
  gz_type_name: "ignition.msgs.Empty"
  direction: "ROS_TO_GZ"
- ros_topic_name: "/jetank2/jenga2/detach"
  gz_topic_name: "/jetank2/jenga2/detach"
  ros_type_name: "std_msgs/msg/Empty"
  gz_type_name: "ignition.msgs.Empty"
  direction: "ROS_TO_GZ"
# Jenga 3
- ros_topic_name: "/jetank2/jenga3/attach"
  gz_topic_name: "/jetank2/jenga3/attach"
  ros_type_name: "std_msgs/msg/Empty"
  gz_type_name: "ignition.msgs.Empty"
  direction: "ROS_TO_GZ"
- ros_topic_name: "/jetank2/jenga3/detach"
  gz_topic_name: "/jetank2/jenga3/detach"
  ros_type_name: "std_msgs/msg/Empty"
  gz_type_name: "ignition.msgs.Empty"
  direction: "ROS_TO_GZ"
# Jenga 4
- ros_topic_name: "/jetank2/jenga4/attach"
  gz_topic_name: "/jetank2/jenga4/attach"
  ros_type_name: "std_msgs/msg/Empty"
  gz_type_name: "ignition.msgs.Empty"
  direction: "ROS_TO_GZ"
- ros_topic_name: "/jetank2/jenga4/detach"
  gz_topic_name: "/jetank2/jenga4/detach"
  ros_type_name: "std_msgs/msg/Empty"
  gz_type_name: "ignition.msgs.Empty"
  direction: "ROS_TO_GZ"
# Jenga 5
- ros_topic_name: "/jetank2/jenga5/attach"
  gz_topic_name: "/jetank2/jenga5/attach"
  ros_type_name: "std_msgs/msg/Empty"
  gz_type_name: "ignition.msgs.Empty"
  direction: "ROS_TO_GZ"
- ros_topic_name: "/jetank2/jenga5/detach"
  gz_topic_name: "/jetank2/jenga5/detach"
  ros_type_name: "std_msgs/msg/Empty"
  gz_type_name: "ignition.msgs.Empty"
  direction: "ROS_TO_GZ"
# Jenga 6
- ros_topic_name: "/jetank2/jenga6/attach"
  gz_topic_name: "/jetank2/jenga6/attach"
  ros_type_name: "std_msgs/msg/Empty"
  gz_type_name: "ignition.msgs.Empty"
  direction: "ROS_TO_GZ"
- ros_topic_name: "/jetank2/jenga6/detach"
  gz_topic_name: "/jetank2/jenga6/detach"
  ros_type_name: "std_msgs/msg/Empty"
  gz_type_name: "ignition.msgs.Empty"
  direction: "ROS_TO_GZ"
# Jenga 7
- ros_topic_name: "/jetank2/jenga7/attach"
  gz_topic_name: "/jetank2/jenga7/attach"
  ros_type_name: "std_msgs/msg/Empty"
  gz_type_name: "ignition.msgs.Empty"
  direction: "ROS_TO_GZ"
- ros_topic_name: "/jetank2/jenga7/detach"
  gz_topic_name: "/jetank2/jenga7/detach"
  ros_type_name: "std_msgs/msg/Empty"
  gz_type_name: "ignition.msgs.Empty"
  direction: "ROS_TO_GZ"
# Jenga 8
- ros_topic_name: "/jetank2/jenga8/attach"
  gz_topic_name: "/jetank2/jenga8/attach"
  ros_type_name: "std_msgs/msg/Empty"
  gz_type_name: "ignition.msgs.Empty"
  direction: "ROS_TO_GZ"
- ros_topic_name: "/jetank2/jenga8/detach"
  gz_topic_name: "/jetank2/jenga8/detach"
  ros_type_name: "std_msgs/msg/Empty"
  gz_type_name: "ignition.msgs.Empty"
  direction: "ROS_TO_GZ"
# Jenga 9
- ros_topic_name: "/jetank2/jenga9/attach"
  gz_topic_name: "/jetank2/jenga9/attach"
  ros_type_name: "std_msgs/msg/Empty"
  gz_type_name: "ignition.msgs.Empty"
  direction: "ROS_TO_GZ"
- ros_topic_name: "/jetank2/jenga9/detach"
  gz_topic_name: "/jetank2/jenga9/detach"
  ros_type_name: "std_msgs/msg/Empty"
  gz_type_name: "ignition.msgs.Empty"
  direction: "ROS_TO_GZ"
# Jenga 10
- ros_topic_name: "/jetank2/jenga10/attach"
  gz_topic_name: "/jetank2/jenga10/attach"
  ros_type_name: "std_msgs/msg/Empty"
  gz_type_name: "ignition.msgs.Empty"
  direction: "ROS_TO_GZ"
- ros_topic_name: "/jetank2/jenga10/detach"
  gz_topic_name: "/jetank2/jenga10/detach"
  ros_type_name: "std_msgs/msg/Empty"
  gz_type_name: "ignition.msgs.Empty"
  direction: "ROS_TO_GZ"

# ===================== RC Car 포즈 (geometry_msgs/Pose) =====================
- ros_topic_name: /rc_car/pose
  gz_topic_name: /model/rc_car/pose
  ros_type_name: geometry_msgs/msg/Pose
  gz_type_name: gz.msgs.Pose
  direction: GZ_TO_ROS

# ===================== Jetank 포즈 -> TF (RViz용) =====================
- ros_topic_name: /tf
  gz_topic_name: /model/jetank1/pose
  ros_type_name: tf2_msgs/msg/TFMessage
  gz_type_name: ignition.msgs.Pose_V
  direction: GZ_TO_ROS

- ros_topic_name: /tf
  gz_topic_name: /model/jetank2/pose
  ros_type_name: tf2_msgs/msg/TFMessage
  gz_type_name: ignition.msgs.Pose_V
  direction: GZ_TO_ROS
  
# ===================== [NEW] 젠가 위치 실시간 동기화 (1~10) =====================
# Jenga 1
- ros_topic_name: /tf
  gz_topic_name: /model/jenga1/pose
  ros_type_name: tf2_msgs/msg/TFMessage
  gz_type_name: ignition.msgs.Pose_V
  direction: GZ_TO_ROS

# Jenga 2
- ros_topic_name: /tf
  gz_topic_name: /model/jenga2/pose
  ros_type_name: tf2_msgs/msg/TFMessage
  gz_type_name: ignition.msgs.Pose_V
  direction: GZ_TO_ROS

# Jenga 3
- ros_topic_name: /tf
  gz_topic_name: /model/jenga3/pose
  ros_type_name: tf2_msgs/msg/TFMessage
  gz_type_name: ignition.msgs.Pose_V
  direction: GZ_TO_ROS

# Jenga 4
- ros_topic_name: /tf
  gz_topic_name: /model/jenga4/pose
  ros_type_name: tf2_msgs/msg/TFMessage
  gz_type_name: ignition.msgs.Pose_V
  direction: GZ_TO_ROS

# ===================== Top-Down View Cameras =====================
- ros_topic_name: /jetank/top_cctv1
  gz_topic_name: /top_camera_1/image
  ros_type_name: sensor_msgs/msg/Image
  gz_type_name: gz.msgs.Image
  direction: GZ_TO_ROS

- ros_topic_name: /jetank/top_cctv2
  gz_topic_name: /top_camera_2/image
  ros_type_name: sensor_msgs/msg/Image
  gz_type_name: gz.msgs.Image
  direction: GZ_TO_ROS
