amcl:
  ros__parameters:
    use_sim_time: true
    base_frame_id: rc_car/rear_axle
    odom_frame_id: rc_car/odom_rf2o
    global_frame_id: map
    scan_topic: /rc_car/scan
    tf_broadcast: true
    set_initial_pose: true
    always_reset_initial_pose: false
    min_particles: 500
    max_particles: 2000
    laser_model_type: likelihood_field
    update_min_d: 0.05
    update_min_a: 0.02
    resample_interval: 1
    transform_tolerance: 0.2
    robot_model_type: "nav2_amcl::DifferentialMotionModel"
    alpha1: 0.2
    alpha2: 0.2
    alpha3: 0.2
    alpha4: 0.2
    alpha5: 0.2
    sigma_hit: 0.2
    z_hit: 0.9
    z_rand: 0.05
    z_max: 0.05
    z_short: 0.05
    laser_min_range: 0.05
    laser_max_range: 30.0
    laser_max_beams: 60
    pf_err: 0.05
    pf_z: 0.99
    save_pose_rate: 1.0
    map_topic: /map
    use_map_topic: false

bt_navigator:
  ros__parameters:
    use_sim_time: true
    global_frame: map
    robot_base_frame: rc_car/rear_axle
    odom_topic: /rc_car/odom_rf2o
    bt_loop_duration: 100
    filter_duration: 0.2
    default_server_timeout: 20
    wait_for_service_timeout: 1000
    introspection_mode: "disabled"
    default_bt_xml_filename: "simple_nav_to_pose.xml"
    default_nav_to_pose_bt_xml: "simple_nav_to_pose.xml"
    default_nav_through_poses_bt_xml: "simple_nav_through_poses.xml"
    plugin_lib_names:
      - nav2_compute_path_to_pose_action_bt_node
      - nav2_compute_path_through_poses_action_bt_node
      - nav2_follow_path_action_bt_node
      - nav2_back_up_action_bt_node
      - nav2_spin_action_bt_node
      - nav2_wait_action_bt_node
      - nav2_assisted_teleop_action_bt_node
      - nav2_clear_costmap_service_bt_node
      - nav2_recovery_node_bt_node
      - nav2_is_stuck_condition_bt_node
      - nav2_goal_reached_condition_bt_node
      - nav2_goal_updated_condition_bt_node
      - nav2_initial_pose_received_condition_bt_node
      - nav2_distance_traveled_condition_bt_node
      - nav2_time_expired_condition_bt_node
      - nav2_smooth_path_action_bt_node
      - nav2_truncate_path_action_bt_node
      - nav2_rate_controller_bt_node
      - nav2_distance_controller_bt_node
      - nav2_speed_controller_bt_node
      - nav2_is_path_valid_condition_bt_node
      - nav2_controller_selector_bt_node
      - nav2_goal_checker_selector_bt_node
      - nav2_smoother_selector_bt_node
      - nav2_path_longer_on_approach_bt_node
      - nav2_pipeline_sequence_bt_node
      - nav2_remove_passed_goals_action_bt_node

controller_server:
  ros__parameters:
    use_sim_time: true
    controller_frequency: 20.0
    costmap_update_timeout: 0.30
    min_x_velocity_threshold: 0.01
    min_y_velocity_threshold: 0.01
    min_theta_velocity_threshold: 0.01
    failure_tolerance: 0.3
    progress_checker_plugins: ["progress_checker"]
    goal_checker_plugins: ["general_goal_checker"]
    controller_plugins: ["FollowPath"]
    use_realtime_priority: false
    cmd_vel_topic: "/rc_car/cmd_vel_raw"
    speed_limit_topic: "speed_limit"
    progress_checker:
      plugin: "nav2_controller::SimpleProgressChecker"
      required_movement_radius: 0.1
      movement_time_allowance: 20.0
    general_goal_checker:
      stateful: True
      plugin: "nav2_controller::SimpleGoalChecker"
      xy_goal_tolerance: 0.04
      yaw_goal_tolerance: 0.1
    FollowPath:
        plugin: "nav2_mppi_controller::MPPIController"
        iteration_count: 1
        time_steps: 56
        model_dt: 0.05
        batch_size: 2000
        vx_std: 0.2
        vy_std: 0.0
        wz_std: 0.4
        vx_max: 0.5
        vx_min: -0.35
        wz_max: 1.9
        temperature: 0.3
        gamma: 0.015
        retry_attempt_limit: 2
        visualize: false
        regenerate_noises: true
        publish_optimal_trajectory: false
        publish_critics_stats: false
        max_robot_pose_search_dist: 5.0
        prune_distance: 1.5
        transform_tolerance: 0.5
        
        # 아커만 로봇 제약 조건
        motion_model: "Ackermann"
        AckermannConstraints:
          min_turning_r: 0.70
        
        # 핵심: 가중치(Critics) 설정
        critics: ["ConstraintCritic", "CostCritic", "GoalCritic", "GoalAngleCritic", "PathAlignCritic", "PathFollowCritic", "PathAngleCritic", "PreferForwardCritic", "TwirlingCritic"]

        ConstraintCritic:
          enabled: true
          cost_power: 1
          cost_weight: 8.0
        
        GoalCritic:
          enabled: true
          cost_power: 1
          cost_weight: 60.0
          threshold_to_consider: 0.3
        
        GoalAngleCritic:
          enabled: true
          cost_power: 1
          cost_weight: 10.0
          threshold_to_consider: 0.3
        
        PreferForwardCritic:
          enabled: true
          cost_power: 1
          cost_weight: 3.0
          threshold_to_consider: 0.8
        
        TwirlingCritic:
          enabled: true
          cost_power: 1
          cost_weight: 5.0
        
        CostCritic:
          enabled: true
          cost_power: 1
          cost_weight: 10.0
          critical_cost: 300.0
          consider_footprint: true
          collision_cost: 1000000.0
          near_goal_distance: 1.0
          trajectory_point_step: 2
        
        PathAlignCritic:
          enabled: true
          cost_power: 1
          cost_weight: 80.0
          max_path_occupancy_ratio: 0.003
          trajectory_point_step: 1
          threshold_to_consider: 0.2
          offset_from_furthest: 0
          use_path_orientations: true
        
        PathFollowCritic:
          enabled: true
          cost_power: 1
          cost_weight: 20.0
          offset_from_furthest: 2
          threshold_to_consider: 0.5
        
        PathAngleCritic:
          enabled: true
          cost_power: 1
          cost_weight: 20.0
          offset_from_furthest: 0
          threshold_to_consider: 0.1
          max_angle_to_furthest: 0.785398
          mode: 2


local_costmap:
  local_costmap:
    ros__parameters:
      use_sim_time: true
      update_frequency: 10.0
      publish_frequency: 10.0
      global_frame: rc_car/odom_rf2o
      robot_base_frame: rc_car/rear_axle
      rolling_window: true
      width: 20
      height: 20
      resolution: 0.01
      # RC Car footprint (rectangle 앞뒤 0.25m, 좌우 0.16m)
      footprint: "[[0.22, 0.07], [0.22, -0.07], [-0.03, -0.07], [-0.03, 0.07]]"
      plugins: ["obstacle_layer", "inflation_layer"]
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        cost_scaling_factor: 8.0
        inflation_radius: 0.05
      obstacle_layer:
        plugin: "nav2_costmap_2d::ObstacleLayer"
        max_obstacle_height: 2.0
        observation_sources: scan
        scan:
          topic: /rc_car/scan
          max_obstacle_height: 2.0
          clearing: true
          marking: true
          data_type: "LaserScan"
          inf_is_valid: true
      always_send_full_costmap: true
      introspection_mode: "disabled"

global_costmap:
  global_costmap:
    ros__parameters:
      use_sim_time: true
      update_frequency: 1.0
      publish_frequency: 1.0
      global_frame: map
      robot_base_frame: rc_car/rear_axle
      # RC Car footprint (rectangle 앞뒤 0.25m, 좌우 0.16m)
      footprint: "[[0.22, 0.07], [0.22, -0.07], [-0.03, -0.07], [-0.03, 0.07]]"
      resolution: 0.05
      track_unknown_space: true
      plugins: ["static_layer", "obstacle_layer", "inflation_layer"]
      obstacle_layer:
        plugin: "nav2_costmap_2d::ObstacleLayer"
        enabled: True
        observation_sources: scan
        scan:
          topic: /rc_car/scan
          max_obstacle_height: 2.0
          clearing: True
          marking: True
          data_type: "LaserScan"
          raytrace_max_range: 2.5
          raytrace_min_range: 0.0
          obstacle_max_range: 2.0
          obstacle_min_range: 0.0
      static_layer:
        plugin: "nav2_costmap_2d::StaticLayer"
        map_subscribe_transient_local: True
      inflation_layer:
        plugin: "nav2_costmap_2d::InflationLayer"
        cost_scaling_factor: 8.0
        inflation_radius: 0.14
      always_send_full_costmap: True
      introspection_mode: "disabled"

# The yaml_filename does not need to be specified since it going to be set by defaults in launch.
# If you'd rather set it in the yaml, remove the default "map" value in the launch file(s).
# file & provide full path to map below. If CLI map configuration or launch default is provided, that will be used.
map_server:
  ros__parameters:
    use_sim_time: true
    yaml_filename: ""
    introspection_mode: "disabled"

keepout_filter_mask_server:
  ros__parameters:
    topic_name: "keepout_filter_mask"
    # yaml_filename: ""

keepout_costmap_filter_info_server:
  ros__parameters:
    type: 0
    filter_info_topic: "keepout_costmap_filter_info"
    mask_topic: "keepout_filter_mask"
    base: 0.0
    multiplier: 1.0

speed_filter_mask_server:
  ros__parameters:
    topic_name: "speed_filter_mask"
    # yaml_filename: ""

speed_costmap_filter_info_server:
  ros__parameters:
    type: 1
    filter_info_topic: "speed_costmap_filter_info"
    mask_topic: "speed_filter_mask"
    base: 100.0
    multiplier: -1.0

map_saver:
  ros__parameters:
    save_map_timeout: 5.0
    free_thresh_default: 0.2
    occupied_thresh_default: 0.55
    map_subscribe_transient_local: True
    introspection_mode: "disabled"

planner_server:
  ros__parameters:
    use_sim_time: true
    allow_partial_planning: true
    expected_planner_frequency: 10.0
    planner_plugins: ["SmacHybrid"]
    costmap_update_timeout: 2.0
    introspection_mode: "disabled"
    SmacHybrid:
      plugin: "nav2_smac_planner/SmacPlannerHybrid"
      tolerance: 0.3
      downsample_costmap: true
      allow_unknown: true
      max_iterations: 10000
      max_on_approach_iterations: 300
      max_planning_time: 2.0
      analytic_expansion_ratio: 4.0
      analytic_expansion_max_length: 4.0
      lookup_table_size: 20.0
      angle_quantization_bins: 96
      minimum_turning_radius: 0.65
      non_straight_penalty: 15.0
      change_penalty: 3.0
      cost_penalty: 2.0
      cache_obstacle_heuristic: true
      allow_reverse_expansion: false

smoother_server:
  ros__parameters:
    smoother_plugins: ["simple_smoother"]
    simple_smoother:
      plugin: "nav2_smoother::SimpleSmoother"
      tolerance: 1.0e-10
      max_its: 1000
      refinement_num: 2
      # True for Hybrid A* or State Lattice to not smooth over directional changes
      enforce_path_inversion: True
      do_refinement: True

behavior_server:
  ros__parameters:
    use_sim_time: true
    local_costmap_topic: local_costmap/costmap_raw
    global_costmap_topic: global_costmap/costmap_raw
    local_footprint_topic: local_costmap/published_footprint
    global_footprint_topic: global_costmap/published_footprint
    cycle_frequency: 10.0
    behavior_plugins: ["spin", "backup", "drive_on_heading", "wait"]
    spin:
      plugin: "nav2_behaviors/Spin"
    backup:
      plugin: "nav2_behaviors/BackUp"
      acceleration_limit: 2.5
      deceleration_limit: -2.5
      minimum_speed: 0.10
    drive_on_heading:
      plugin: "nav2_behaviors/DriveOnHeading"
      acceleration_limit: 2.5
      deceleration_limit: -2.5
      minimum_speed: 0.10
    wait:
      plugin: "nav2_behaviors/Wait"
    assisted_teleop:
      plugin: "nav2_behaviors/AssistedTeleop"
    local_frame: rc_car/odom_rf2o
    global_frame: map
    robot_base_frame: rc_car/rear_axle
    transform_tolerance: 0.5
    simulate_ahead_time: 2.0
    max_rotational_vel: 1.0
    min_rotational_vel: 0.4
    rotational_acc_lim: 3.2

waypoint_follower:
  ros__parameters:
    use_sim_time: true
    loop_rate: 20
    stop_on_failure: false
    introspection_mode: "disabled"
    waypoint_task_executor_plugin: "wait_at_waypoint"
    wait_at_waypoint:
      plugin: "nav2_waypoint_follower::WaitAtWaypoint"
      enabled: True
      waypoint_pause_duration: 200

lifecycle_manager:
  ros__parameters:
    use_sim_time: true
    autostart: true
    node_names: [
      "controller_server",
      "planner_server",
      "behavior_server",
      "bt_navigator",
      "waypoint_follower",
      "smoother_server",
      "map_server",
      "amcl"
    ]

route_server:
  ros__parameters:
    # The graph_filepath does not need to be specified since it going to be set by defaults in launch.
    # If you'd rather set it in the yaml, remove the default "graph" value in the launch file(s).
    # file & provide full path to map below. If graph config or launch default is provided, it is used
    # graph_filepath: $(find-pkg-share nav2_route)/graphs/aws_graph.geojson
    boundary_radius_to_achieve_node: 1.0
    radius_to_achieve_node: 2.0
    smooth_corners: true
    operations: ["AdjustSpeedLimit", "ReroutingService", "CollisionMonitor"]
    ReroutingService:
      plugin: "nav2_route::ReroutingService"
    AdjustSpeedLimit:
      plugin: "nav2_route::AdjustSpeedLimit"
    CollisionMonitor:
      plugin: "nav2_route::CollisionMonitor"
      max_collision_dist: 0.007
    edge_cost_functions: ["DistanceScorer", "CostmapScorer"]
    DistanceScorer:
      plugin: "nav2_route::DistanceScorer"
    CostmapScorer:
      plugin: "nav2_route::CostmapScorer"

velocity_smoother:
  ros__parameters:
    smoothing_frequency: 20.0
    scale_velocities: False
    feedback: "OPEN_LOOP"
    max_velocity: [0.5, 0.0, 2.0]
    min_velocity: [-0.5, 0.0, -2.0]
    max_accel: [2.5, 0.0, 3.2]
    max_decel: [-2.5, 0.0, -3.2]
    odom_topic: "/rc_car/odom_rf2o"
    odom_duration: 0.1
    deadband_velocity: [0.0, 0.0, 0.0]
    velocity_timeout: 1.0
    cmd_vel_in_topic: "/rc_car/cmd_vel_raw"
    cmd_vel_out_topic: "/rc_car/cmd_vel_smoothed"

collision_monitor:
  ros__parameters:
    enabled: True
    base_frame_id: "rc_car/rear_axle"
    odom_frame_id: "rc_car/odom_rf2o"
    cmd_vel_in_topic: "/rc_car/cmd_vel_smoothed"
    cmd_vel_out_topic: "/rc_car/cmd_vel"
    state_topic: "collision_monitor_state"
    transform_tolerance: 0.2
    source_timeout: 1.0
    base_shift_correction: True
    stop_pub_timeout: 2.0
    # 충돌 감지 거리 축소
    max_collision_dist: 0.007
    # Polygons represent zone around the robot for "stop", "slowdown" and "limit" action types,
    # and robot footprint for "approach" action type.
    polygons: ["FootprintApproach"]
    FootprintApproach:
      type: "polygon"
      action_type: "approach"
      footprint_topic: "local_costmap/published_footprint"
      # 더 가까운 접근 허용: 예상 충돌까지 여유 시간을 줄이고 시뮬레이션 스텝도 짧게
      time_before_collision: 0.1
      simulation_time_step: 0.02
      min_points: 6
      visualize: False
      enabled: True
    observation_sources: ["scan"]
    scan:
      type: "scan"
      topic: "/rc_car/scan"
      min_height: 0.15
      max_height: 2.0
      enabled: True

docking_server:
  ros__parameters:
    controller_frequency: 50.0
    initial_perception_timeout: 5.0
    wait_charge_timeout: 5.0
    dock_approach_timeout: 30.0
    undock_linear_tolerance: 0.002
    undock_angular_tolerance: 0.1
    max_retries: 3
    base_frame: "rc_car/rear_axle"
    fixed_frame: "odom"
    dock_prestaging_tolerance: 0.5
    introspection_mode: "disabled"

    # Types of docks
    dock_plugins: ["simple_charging_dock"]
    simple_charging_dock:
      plugin: "opennav_docking::SimpleChargingDock"
      docking_threshold: 0.05
      staging_x_offset: -0.7
      use_external_detection_pose: true
      use_battery_status: false # true
      use_stall_detection: false # true
      dock_direction: "forward"

      external_detection_timeout: 1.0
      external_detection_translation_x: -0.18
      external_detection_translation_y: 0.0
      external_detection_rotation_roll: -1.57
      external_detection_rotation_pitch: -1.57
      external_detection_rotation_yaw: 0.0
      filter_coef: 0.1

    # Dock instances
    # The following example illustrates configuring dock instances.
    # docks: ['home_dock']  # Input your docks here
    # home_dock:
    #   type: 'simple_charging_dock'
    #   frame: map
    #   pose: [0.0, 0.0, 0.0]

    controller:
      k_phi: 3.0
      k_delta: 2.0
      v_linear_min: 0.15
      v_linear_max: 0.15
      use_collision_detection: true
      costmap_topic: "local_costmap/costmap_raw"
      footprint_topic: "local_costmap/published_footprint"
      transform_tolerance: 0.1
      projection_time: 5.0
      simulation_step: 0.1
      dock_collision_threshold: 0.3

loopback_simulator:
  ros__parameters:
    base_frame_id: "rc_car/rear_axle"
    odom_frame_id: "odom"
    map_frame_id: "map"
    scan_frame_id: "base_scan" # tb4_loopback_simulator.launch.py remaps to 'rplidar_link'
    update_duration: 0.02
    scan_range_min: 0.05
    scan_range_max: 30.0
    scan_angle_min: -3.1415
    scan_angle_max: 3.1415
    scan_angle_increment: 0.02617
    scan_use_inf: true
